language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
virtualenv:
  - system_site_packages: true
before_install:
  sudo apt-get -qq install python-pandas
install:
  - pip install coveralls
script:
  - coverage run --source=pubchempy setup.py test
after_success:
  - coveralls
