language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  - OPTIONAL_DEPS=true
  - OPTIONAL_DEPS=false
install:
  - pip install coveralls pytest
  - if [ "$OPTIONAL_DEPS" = true ]; then pip install pandas; fi
script:
  - coverage run --source=pubchempy -m pytest
after_success:
  - coveralls
